-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 10:24:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8 ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`usuaris` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom_usuari` VARCHAR(45) NOT NULL,
  `data_naix` DATE NOT NULL,
  `sexe` SET('masculi', 'femeni', 'altres') NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`canals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`canals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` MEDIUMTEXT NULL DEFAULT NULL,
  `creat` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `usuari` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuari_UNIQUE` (`usuari` ASC) ,
  INDEX `FK_CAUSUARI_idx` (`usuari` ASC) ,
  CONSTRAINT `FK_CAUSUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`comentari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comentari` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comentari` MEDIUMTEXT NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`comentaris_likes_dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comentaris_likes_dislikes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuari` INT(11) NOT NULL,
  `comentari` INT(11) NOT NULL,
  `status` SET('like', 'dislike') NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuari_UNIQUE` (`usuari` ASC) ,
  UNIQUE INDEX `comentari_UNIQUE` (`comentari` ASC) ,
  INDEX `FK_CLUSUARI_idx` (`usuari` ASC) ,
  INDEX `FK_CLCOMENTARI_idx` (`comentari` ASC) ,
  CONSTRAINT `FK_CLCOMENTARI`
    FOREIGN KEY (`comentari`)
    REFERENCES `youtube`.`comentari` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CLUSUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(120) NOT NULL,
  `descripcio` MEDIUMTEXT NULL DEFAULT NULL,
  `grandaria` DECIMAL(10,2) NOT NULL,
  `nom_arxiu` VARCHAR(45) NOT NULL,
  `durada` TIME NOT NULL,
  `thumbnail` VARCHAR(250) NOT NULL,
  `reproduccions` INT(11) NOT NULL DEFAULT 0,
  `likes` INT(11) NOT NULL DEFAULT 0,
  `dislikes` INT(11) NOT NULL DEFAULT 0,
  `estat` SET('public', 'ocult', 'privat') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`comentaris_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comentaris_video` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuari` INT(11) NOT NULL,
  `comentari` INT(11) NOT NULL,
  `video` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_CUSUARI_idx` (`usuari` ASC) ,
  INDEX `FK_CCOMENTARI_idx` (`comentari` ASC) ,
  INDEX `FK_CVIDEO_idx` (`video` ASC) ,
  CONSTRAINT `FK_CCOMENTARI`
    FOREIGN KEY (`comentari`)
    REFERENCES `youtube`.`comentari` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CUSUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CVIDEO`
    FOREIGN KEY (`video`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`etiquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`etiquetes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`likes_dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`likes_dislikes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuari` INT(11) NOT NULL,
  `video` INT(11) NOT NULL,
  `status` SET('like', 'dislike') NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuari_UNIQUE` (`usuari` ASC) ,
  UNIQUE INDEX `video_UNIQUE` (`video` ASC) ,
  INDEX `FK_LUSUARI_idx` (`usuari` ASC) ,
  INDEX `FK_LVIDEO_idx` (`video` ASC) ,
  CONSTRAINT `FK_LUSUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LVIDEO`
    FOREIGN KEY (`video`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`playlists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `creada` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `estat` SET('publica', 'privada') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`playlist_usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`playlist_usuaris` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuari` INT(11) NOT NULL,
  `playlist` INT(11) NOT NULL,
  `video` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PLUSUARI_idx` (`usuari` ASC) ,
  INDEX `FK_PLPLAYLIST_idx` (`playlist` ASC) ,
  INDEX `FK_PLVIDEO_idx` (`video` ASC) ,
  CONSTRAINT `FK_PLPLAYLIST`
    FOREIGN KEY (`playlist`)
    REFERENCES `youtube`.`playlists` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PLUSUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PLVIDEO`
    FOREIGN KEY (`video`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`publicacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`publicacio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuari` INT(11) NOT NULL,
  `video` INT(11) NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `canal` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_USUARI_idx` (`usuari` ASC) ,
  INDEX `FK_PVIDEO_idx` (`video` ASC) ,
  INDEX `FK_CANALPUB_idx` (`canal` ASC) ,
  CONSTRAINT `FK_CANALPUB`
    FOREIGN KEY (`canal`)
    REFERENCES `youtube`.`canals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PVIDEO`
    FOREIGN KEY (`video`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`subscripcions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`subscripcions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuari` INT(11) NOT NULL,
  `canal` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_SUSUARI_idx` (`usuari` ASC) ,
  INDEX `FK_SCANAL_idx` (`canal` ASC) ,
  CONSTRAINT `FK_SCANAL`
    FOREIGN KEY (`canal`)
    REFERENCES `youtube`.`canals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SUSUARI`
    FOREIGN KEY (`usuari`)
    REFERENCES `youtube`.`usuaris` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `youtube`.`videos_etiquetats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videos_etiquetats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `video` INT(11) NOT NULL,
  `etiqueta` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_VIDEO_idx` (`video` ASC) ,
  INDEX `FK_ETIQUETA_idx` (`etiqueta` ASC) ,
  CONSTRAINT `FK_ETIQUETA`
    FOREIGN KEY (`etiqueta`)
    REFERENCES `youtube`.`etiquetes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_VIDEO`
    FOREIGN KEY (`video`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
